/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.personal.stockmarketsimulator;

import java.awt.Color;
import java.awt.Dialog;
import javax.swing.JOptionPane;
/**
 * @author Rushi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JLayeredPane();
        StockMarketPanel = new javax.swing.JPanel();
        StockMarketTitleLabel = new javax.swing.JLabel();
        StocksPane = new javax.swing.JPanel();
        popularStock1 = new javax.swing.JPanel();
        popularStock1Symbol = new javax.swing.JLabel();
        popularStockCurrentPrice = new javax.swing.JLabel();
        popularStock1PercentChange = new javax.swing.JLabel();
        popularStock1Open = new javax.swing.JLabel();
        popularStock1PreviousClose = new javax.swing.JLabel();
        popularStock2 = new javax.swing.JPanel();
        popularStock2Symbol = new javax.swing.JLabel();
        popularStock2CurrentPrice = new javax.swing.JLabel();
        popularStock2PercentChange = new javax.swing.JLabel();
        popularStock2Open = new javax.swing.JLabel();
        popularStock2PreviousClose = new javax.swing.JLabel();
        popularStock3 = new javax.swing.JPanel();
        popularStock3Symbol = new javax.swing.JLabel();
        popularStock3CurrentPrice = new javax.swing.JLabel();
        popularStock3PercentChange = new javax.swing.JLabel();
        popularStock3Open = new javax.swing.JLabel();
        popularStock3PreviousClose = new javax.swing.JLabel();
        stockSearchField = new javax.swing.JTextField();
        PortfolioPanel = new javax.swing.JPanel();
        AccountValueBox = new javax.swing.JPanel();
        AccountValueLabel = new javax.swing.JLabel();
        AccountValueLabelText = new javax.swing.JLabel();
        StockValueBox = new javax.swing.JPanel();
        PortfolioBalanceLabelText = new javax.swing.JLabel();
        PortfolioBalanceLabel = new javax.swing.JLabel();
        PortfolioTitleLabel = new javax.swing.JLabel();
        StocksLabel = new javax.swing.JLabel();
        stockPortfolioPane = new javax.swing.JScrollPane();
        stockPortfolioTable = new javax.swing.JTable();
        Sidebar = new javax.swing.JPanel();
        SidebarPortfolioBox = new javax.swing.JPanel();
        SidebarPortfolioLabel = new javax.swing.JLabel();
        SidebarStockMarketBox = new javax.swing.JPanel();
        SidbarStockMarketLabel = new javax.swing.JLabel();
        SidebarWatchlistBox = new javax.swing.JPanel();
        SidebarWatchlistLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 249));
        setMaximumSize(new java.awt.Dimension(1152, 700));
        setMinimumSize(new java.awt.Dimension(1152, 700));
        setPreferredSize(new java.awt.Dimension(1152, 700));

        MainPane.setMaximumSize(new java.awt.Dimension(998, 712));
        MainPane.setMinimumSize(new java.awt.Dimension(998, 712));
        MainPane.setPreferredSize(new java.awt.Dimension(998, 700));
        MainPane.setSize(new java.awt.Dimension(998, 700));

        StockMarketPanel.setBackground(new java.awt.Color(245, 247, 249));
        StockMarketPanel.setMaximumSize(new java.awt.Dimension(986, 700));
        StockMarketPanel.setPreferredSize(new java.awt.Dimension(986, 700));
        StockMarketPanel.setSize(new java.awt.Dimension(986, 700));
        this.StockMarketPanel.setVisible(false);

        StockMarketTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 50)); // NOI18N
        StockMarketTitleLabel.setText("Stock Market");

        StocksPane.setBackground(new java.awt.Color(245, 247, 249));
        StocksPane.setMaximumSize(new java.awt.Dimension(916, 700));
        StocksPane.setMinimumSize(new java.awt.Dimension(916, 700));
        StocksPane.setPreferredSize(new java.awt.Dimension(916, 700));
        StocksPane.setSize(new java.awt.Dimension(916, 700));
        StocksPane.setLayout(new java.awt.GridLayout(3, 1, 50, 50));

        popularStock1.setBackground(new java.awt.Color(255, 255, 255));

        popularStock1Symbol.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        popularStock1Symbol.setText("Symbol 1");

        popularStockCurrentPrice.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStockCurrentPrice.setText("Current Price:");

        popularStock1PercentChange.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock1PercentChange.setText("Percent Change:");

        popularStock1Open.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock1Open.setText("Open:");

        popularStock1PreviousClose.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock1PreviousClose.setText("Previous Close:");

        javax.swing.GroupLayout popularStock1Layout = new javax.swing.GroupLayout(popularStock1);
        popularStock1.setLayout(popularStock1Layout);
        popularStock1Layout.setHorizontalGroup(
            popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock1Layout.createSequentialGroup()
                .addGroup(popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popularStock1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(popularStock1Symbol))
                    .addGroup(popularStock1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popularStockCurrentPrice)
                            .addComponent(popularStock1PercentChange))
                        .addGap(282, 282, 282)
                        .addGroup(popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popularStock1PreviousClose)
                            .addComponent(popularStock1Open))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        popularStock1Layout.setVerticalGroup(
            popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(popularStock1Symbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularStockCurrentPrice)
                    .addComponent(popularStock1Open))
                .addGap(12, 12, 12)
                .addGroup(popularStock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularStock1PercentChange)
                    .addComponent(popularStock1PreviousClose))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        StocksPane.add(popularStock1);

        popularStock2.setBackground(new java.awt.Color(255, 255, 255));

        popularStock2Symbol.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        popularStock2Symbol.setText("Symbol 2");

        popularStock2CurrentPrice.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock2CurrentPrice.setText("Current Price:");

        popularStock2PercentChange.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock2PercentChange.setText("Percent Change:");

        popularStock2Open.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock2Open.setText("Open:");

        popularStock2PreviousClose.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock2PreviousClose.setText("Previous Close:");

        javax.swing.GroupLayout popularStock2Layout = new javax.swing.GroupLayout(popularStock2);
        popularStock2.setLayout(popularStock2Layout);
        popularStock2Layout.setHorizontalGroup(
            popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popularStock2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popularStock2PercentChange)
                            .addComponent(popularStock2CurrentPrice))
                        .addGap(280, 280, 280)
                        .addGroup(popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popularStock2Open)
                            .addComponent(popularStock2PreviousClose)))
                    .addComponent(popularStock2Symbol))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        popularStock2Layout.setVerticalGroup(
            popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(popularStock2Symbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularStock2CurrentPrice)
                    .addComponent(popularStock2Open))
                .addGap(12, 12, 12)
                .addGroup(popularStock2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularStock2PercentChange)
                    .addComponent(popularStock2PreviousClose))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        StocksPane.add(popularStock2);

        popularStock3.setBackground(new java.awt.Color(255, 255, 255));

        popularStock3Symbol.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        popularStock3Symbol.setText("Symbol 3");

        popularStock3CurrentPrice.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock3CurrentPrice.setText("Current Price:");

        popularStock3PercentChange.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock3PercentChange.setText("Percent Change:");

        popularStock3Open.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock3Open.setText("Open:");

        popularStock3PreviousClose.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        popularStock3PreviousClose.setText("Previous Close:");

        javax.swing.GroupLayout popularStock3Layout = new javax.swing.GroupLayout(popularStock3);
        popularStock3.setLayout(popularStock3Layout);
        popularStock3Layout.setHorizontalGroup(
            popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popularStock3Symbol)
                    .addGroup(popularStock3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popularStock3CurrentPrice)
                            .addComponent(popularStock3PercentChange))))
                .addGap(282, 282, 282)
                .addGroup(popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popularStock3Layout.createSequentialGroup()
                        .addComponent(popularStock3Open)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(popularStock3Layout.createSequentialGroup()
                        .addComponent(popularStock3PreviousClose)
                        .addGap(0, 273, Short.MAX_VALUE))))
        );
        popularStock3Layout.setVerticalGroup(
            popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popularStock3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(popularStock3Symbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popularStock3CurrentPrice)
                    .addComponent(popularStock3Open))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popularStock3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popularStock3PreviousClose)
                    .addComponent(popularStock3PercentChange))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        StocksPane.add(popularStock3);

        stockSearchField.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        stockSearchField.setForeground(new java.awt.Color(196, 196, 196));
        stockSearchField.setText("Search Stock Symbol");
        stockSearchField.setMaximumSize(new java.awt.Dimension(229, 35));
        stockSearchField.setMinimumSize(new java.awt.Dimension(229, 35));
        stockSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFocusLost(evt);
            }
        });
        stockSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchClicked(evt);
            }
        });
        stockSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockSearchFieldActionPerformed(evt);
            }
        });
        stockSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchEnterPressed(evt);
            }
        });

        javax.swing.GroupLayout StockMarketPanelLayout = new javax.swing.GroupLayout(StockMarketPanel);
        StockMarketPanel.setLayout(StockMarketPanelLayout);
        StockMarketPanelLayout.setHorizontalGroup(
            StockMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockMarketPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(StockMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StockMarketTitleLabel)
                    .addComponent(StocksPane, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        StockMarketPanelLayout.setVerticalGroup(
            StockMarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockMarketPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(StockMarketTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(stockSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StocksPane, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        PortfolioPanel.setBackground(new java.awt.Color(245, 247, 249));
        PortfolioPanel.setFocusTraversalKeysEnabled(false);
        PortfolioPanel.setMaximumSize(new java.awt.Dimension(986, 700));
        PortfolioPanel.setMinimumSize(new java.awt.Dimension(986, 700));
        PortfolioPanel.setPreferredSize(new java.awt.Dimension(986, 700));

        AccountValueBox.setBackground(new java.awt.Color(255, 255, 255));
        AccountValueBox.setPreferredSize(new java.awt.Dimension(406, 227));
        AccountValueBox.setSize(new java.awt.Dimension(406, 227));

        AccountValueLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 60)); // NOI18N
        AccountValueLabel.setText("$10,000");

        AccountValueLabelText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        AccountValueLabelText.setText("Account Balance");

        javax.swing.GroupLayout AccountValueBoxLayout = new javax.swing.GroupLayout(AccountValueBox);
        AccountValueBox.setLayout(AccountValueBoxLayout);
        AccountValueBoxLayout.setHorizontalGroup(
            AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountValueBoxLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountValueBoxLayout.createSequentialGroup()
                        .addComponent(AccountValueLabel)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountValueBoxLayout.createSequentialGroup()
                        .addComponent(AccountValueLabelText)
                        .addGap(90, 90, 90))))
        );
        AccountValueBoxLayout.setVerticalGroup(
            AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountValueBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AccountValueLabelText)
                .addGap(31, 31, 31)
                .addComponent(AccountValueLabel)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        StockValueBox.setBackground(new java.awt.Color(255, 255, 255));
        StockValueBox.setPreferredSize(new java.awt.Dimension(406, 227));
        StockValueBox.setSize(new java.awt.Dimension(406, 227));

        PortfolioBalanceLabelText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        PortfolioBalanceLabelText.setText("Portfolio Balance");

        PortfolioBalanceLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 60)); // NOI18N
        PortfolioBalanceLabel.setText("$5,000");

        javax.swing.GroupLayout StockValueBoxLayout = new javax.swing.GroupLayout(StockValueBox);
        StockValueBox.setLayout(StockValueBoxLayout);
        StockValueBoxLayout.setHorizontalGroup(
            StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockValueBoxLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PortfolioBalanceLabel)
                    .addComponent(PortfolioBalanceLabelText))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        StockValueBoxLayout.setVerticalGroup(
            StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockValueBoxLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PortfolioBalanceLabelText)
                .addGap(39, 39, 39)
                .addComponent(PortfolioBalanceLabel)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PortfolioTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 50)); // NOI18N
        PortfolioTitleLabel.setText("Portfolio");

        StocksLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 50)); // NOI18N
        StocksLabel.setText("Stocks");

        stockPortfolioTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stockPortfolioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stockPortfolioPane.setViewportView(stockPortfolioTable);

        javax.swing.GroupLayout PortfolioPanelLayout = new javax.swing.GroupLayout(PortfolioPanel);
        PortfolioPanel.setLayout(PortfolioPanelLayout);
        PortfolioPanelLayout.setHorizontalGroup(
            PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortfolioPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PortfolioPanelLayout.createSequentialGroup()
                        .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StocksLabel)
                            .addComponent(PortfolioTitleLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PortfolioPanelLayout.createSequentialGroup()
                        .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stockPortfolioPane)
                            .addGroup(PortfolioPanelLayout.createSequentialGroup()
                                .addComponent(StockValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(AccountValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        PortfolioPanelLayout.setVerticalGroup(
            PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortfolioPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(PortfolioTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StockValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(StocksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(stockPortfolioPane, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        MainPane.setLayer(StockMarketPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPane.setLayer(PortfolioPanel, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addComponent(PortfolioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockMarketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StockMarketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortfolioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));
        Sidebar.setMaximumSize(new java.awt.Dimension(166, 700));
        Sidebar.setPreferredSize(new java.awt.Dimension(166, 700));

        SidebarPortfolioBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPortfolioBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarPortfolioBoxEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarPortfolioBoxExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                none(evt);
                PortfolioPressed(evt);
            }
        });

        SidebarPortfolioLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidebarPortfolioLabel.setText("Portfolio");

        javax.swing.GroupLayout SidebarPortfolioBoxLayout = new javax.swing.GroupLayout(SidebarPortfolioBox);
        SidebarPortfolioBox.setLayout(SidebarPortfolioBoxLayout);
        SidebarPortfolioBoxLayout.setHorizontalGroup(
            SidebarPortfolioBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPortfolioBoxLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(SidebarPortfolioLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidebarPortfolioBoxLayout.setVerticalGroup(
            SidebarPortfolioBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPortfolioBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidebarPortfolioLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidebarStockMarketBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarStockMarketBox.setPreferredSize(new java.awt.Dimension(166, 43));
        SidebarStockMarketBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockMarketButtonEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockMarketButtonExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StockMarketPressed(evt);
            }
        });

        SidbarStockMarketLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidbarStockMarketLabel.setText("Stock Market");

        javax.swing.GroupLayout SidebarStockMarketBoxLayout = new javax.swing.GroupLayout(SidebarStockMarketBox);
        SidebarStockMarketBox.setLayout(SidebarStockMarketBoxLayout);
        SidebarStockMarketBoxLayout.setHorizontalGroup(
            SidebarStockMarketBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarStockMarketBoxLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(SidbarStockMarketLabel)
                .addContainerGap())
        );
        SidebarStockMarketBoxLayout.setVerticalGroup(
            SidebarStockMarketBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarStockMarketBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SidbarStockMarketLabel)
                .addContainerGap())
        );

        SidebarWatchlistBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarWatchlistBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarWatchlistBoxEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarWatchlistBoxExit(evt);
            }
        });

        SidebarWatchlistLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidebarWatchlistLabel.setText("My Watchlist");

        javax.swing.GroupLayout SidebarWatchlistBoxLayout = new javax.swing.GroupLayout(SidebarWatchlistBox);
        SidebarWatchlistBox.setLayout(SidebarWatchlistBoxLayout);
        SidebarWatchlistBoxLayout.setHorizontalGroup(
            SidebarWatchlistBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarWatchlistBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SidebarWatchlistLabel)
                .addContainerGap())
        );
        SidebarWatchlistBoxLayout.setVerticalGroup(
            SidebarWatchlistBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarWatchlistBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidebarWatchlistLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 50)); // NOI18N
        jLabel1.setText("SMS");

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidebarPortfolioBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SidebarStockMarketBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(SidebarWatchlistBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(SidebarPortfolioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(SidebarStockMarketBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(SidebarWatchlistBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StockMarketButtonEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketButtonEnter
        // HOVERED    
        this.SidebarStockMarketBox.setBackground(Color.BLACK);
        this.SidbarStockMarketLabel.setForeground(Color.WHITE);
        
        //unhovered
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
        
        //unhovered
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_StockMarketButtonEnter

    private void StockMarketButtonExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketButtonExit
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_StockMarketButtonExit

    private void SidebarPortfolioBoxEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPortfolioBoxEnter
        //unhovered
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
        
        //HOVER
        this.SidebarPortfolioBox.setBackground(Color.BLACK);
        this.SidebarPortfolioLabel.setForeground(Color.WHITE);
        
        //unhovered
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarPortfolioBoxEnter

    private void SidebarPortfolioBoxExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPortfolioBoxExit
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarPortfolioBoxExit

    private void SidebarWatchlistBoxEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarWatchlistBoxEnter
        //unhovered      
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
        
        //unhovered
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
        
        //HOVERED
        this.SidebarWatchlistBox.setBackground(Color.BLACK);
        this.SidebarWatchlistLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_SidebarWatchlistBoxEnter

    private void SidebarWatchlistBoxExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarWatchlistBoxExit
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarWatchlistBoxExit

    private void StockMarketPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketPressed
        this.PortfolioPanel.setVisible(false);
        this.StockMarketPanel.setVisible(true);
        
    }//GEN-LAST:event_StockMarketPressed

    private void PortfolioPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PortfolioPressed
        // TODO add your handling code here:
    	this.PortfolioPanel.setVisible(true);
        this.StockMarketPanel.setVisible(false);
    }//GEN-LAST:event_PortfolioPressed

    private void stockSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockSearchFieldActionPerformed

    private void SearchClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchClicked
        this.stockSearchField.setText("");
    }//GEN-LAST:event_SearchClicked

    private void SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusLost
        this.stockSearchField.setText("Search Stock Symbol");
    }//GEN-LAST:event_SearchFocusLost

    private void SearchEnterPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchEnterPressed
//        System.out.println(evt.getKeyChar());
        if(evt.getKeyChar()=='\n'){
            JOptionPane.showMessageDialog(this, stockSearchField.getText());
            this.requestFocus();
        }
    }//GEN-LAST:event_SearchEnterPressed
    private void none(java.awt.event.MouseEvent evt){}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountValueBox;
    private javax.swing.JLabel AccountValueLabel;
    private javax.swing.JLabel AccountValueLabelText;
    private javax.swing.JLayeredPane MainPane;
    private javax.swing.JLabel PortfolioBalanceLabel;
    private javax.swing.JLabel PortfolioBalanceLabelText;
    private javax.swing.JPanel PortfolioPanel;
    private javax.swing.JLabel PortfolioTitleLabel;
    private javax.swing.JLabel SidbarStockMarketLabel;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel SidebarPortfolioBox;
    private javax.swing.JLabel SidebarPortfolioLabel;
    private javax.swing.JPanel SidebarStockMarketBox;
    private javax.swing.JPanel SidebarWatchlistBox;
    private javax.swing.JLabel SidebarWatchlistLabel;
    private javax.swing.JPanel StockMarketPanel;
    private javax.swing.JLabel StockMarketTitleLabel;
    private javax.swing.JPanel StockValueBox;
    private javax.swing.JLabel StocksLabel;
    private javax.swing.JPanel StocksPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel popularStock1;
    private javax.swing.JLabel popularStock1Open;
    private javax.swing.JLabel popularStock1PercentChange;
    private javax.swing.JLabel popularStock1PreviousClose;
    private javax.swing.JLabel popularStock1Symbol;
    private javax.swing.JPanel popularStock2;
    private javax.swing.JLabel popularStock2CurrentPrice;
    private javax.swing.JLabel popularStock2Open;
    private javax.swing.JLabel popularStock2PercentChange;
    private javax.swing.JLabel popularStock2PreviousClose;
    private javax.swing.JLabel popularStock2Symbol;
    private javax.swing.JPanel popularStock3;
    private javax.swing.JLabel popularStock3CurrentPrice;
    private javax.swing.JLabel popularStock3Open;
    private javax.swing.JLabel popularStock3PercentChange;
    private javax.swing.JLabel popularStock3PreviousClose;
    private javax.swing.JLabel popularStock3Symbol;
    private javax.swing.JLabel popularStockCurrentPrice;
    private javax.swing.JScrollPane stockPortfolioPane;
    private javax.swing.JTable stockPortfolioTable;
    private javax.swing.JTextField stockSearchField;
    // End of variables declaration//GEN-END:variables
}