/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.personal.stockmarketsimulator;

import java.awt.Color;
/**
 * @author Rushi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        SidebarPortfolioBox = new javax.swing.JPanel();
        SidebarPortfolioLabel = new javax.swing.JLabel();
        SidebarStockMarketBox = new javax.swing.JPanel();
        SidbarStockMarketLabel = new javax.swing.JLabel();
        SidebarWatchlistBox = new javax.swing.JPanel();
        SidebarWatchlistLabel = new javax.swing.JLabel();
        PortfolioPanel = new javax.swing.JPanel();
        AccountValueBox = new javax.swing.JPanel();
        AccountValueLabel = new javax.swing.JLabel();
        AccountValueLabelText = new javax.swing.JLabel();
        StockValueBox = new javax.swing.JPanel();
        PortfolioBalanceLabelText = new javax.swing.JLabel();
        PortfolioBalanceLabel = new javax.swing.JLabel();
        PortfolioTitleLabel = new javax.swing.JLabel();
        StocksLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 249));
        setMaximumSize(new java.awt.Dimension(1152, 700));
        setMinimumSize(new java.awt.Dimension(1152, 700));
        setPreferredSize(new java.awt.Dimension(1152, 700));

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));
        Sidebar.setPreferredSize(new java.awt.Dimension(166, 700));

        SidebarPortfolioBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPortfolioBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarPortfolioBoxEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarPortfolioBoxExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                none(evt);
                PortfolioPressed(evt);
            }
        });

        SidebarPortfolioLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidebarPortfolioLabel.setText("Portfolio");

        javax.swing.GroupLayout SidebarPortfolioBoxLayout = new javax.swing.GroupLayout(SidebarPortfolioBox);
        SidebarPortfolioBox.setLayout(SidebarPortfolioBoxLayout);
        SidebarPortfolioBoxLayout.setHorizontalGroup(
            SidebarPortfolioBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPortfolioBoxLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(SidebarPortfolioLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidebarPortfolioBoxLayout.setVerticalGroup(
            SidebarPortfolioBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarPortfolioBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidebarPortfolioLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidebarStockMarketBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarStockMarketBox.setPreferredSize(new java.awt.Dimension(166, 43));
        SidebarStockMarketBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockMarketButtonEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockMarketButtonExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StockMarketPressed(evt);
            }
        });

        SidbarStockMarketLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidbarStockMarketLabel.setText("Stock Market");

        javax.swing.GroupLayout SidebarStockMarketBoxLayout = new javax.swing.GroupLayout(SidebarStockMarketBox);
        SidebarStockMarketBox.setLayout(SidebarStockMarketBoxLayout);
        SidebarStockMarketBoxLayout.setHorizontalGroup(
            SidebarStockMarketBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarStockMarketBoxLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(SidbarStockMarketLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        SidebarStockMarketBoxLayout.setVerticalGroup(
            SidebarStockMarketBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarStockMarketBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SidbarStockMarketLabel)
                .addContainerGap())
        );

        SidebarWatchlistBox.setBackground(new java.awt.Color(255, 255, 255));
        SidebarWatchlistBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarWatchlistBoxEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarWatchlistBoxExit(evt);
            }
        });

        SidebarWatchlistLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        SidebarWatchlistLabel.setText("My Watchlist");

        javax.swing.GroupLayout SidebarWatchlistBoxLayout = new javax.swing.GroupLayout(SidebarWatchlistBox);
        SidebarWatchlistBox.setLayout(SidebarWatchlistBoxLayout);
        SidebarWatchlistBoxLayout.setHorizontalGroup(
            SidebarWatchlistBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarWatchlistBoxLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(SidebarWatchlistLabel)
                .addGap(12, 12, 12))
        );
        SidebarWatchlistBoxLayout.setVerticalGroup(
            SidebarWatchlistBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarWatchlistBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidebarWatchlistLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidebarPortfolioBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SidebarStockMarketBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addComponent(SidebarWatchlistBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(SidebarPortfolioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(SidebarStockMarketBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(SidebarWatchlistBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PortfolioPanel.setBackground(new java.awt.Color(245, 247, 249));
        PortfolioPanel.setMaximumSize(new java.awt.Dimension(986, 700));
        PortfolioPanel.setMinimumSize(new java.awt.Dimension(986, 700));
        PortfolioPanel.setPreferredSize(new java.awt.Dimension(986, 700));

        AccountValueBox.setBackground(new java.awt.Color(255, 255, 255));
        AccountValueBox.setPreferredSize(new java.awt.Dimension(406, 227));
        AccountValueBox.setSize(new java.awt.Dimension(406, 227));

        AccountValueLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 60)); // NOI18N
        AccountValueLabel.setText("$10,000");

        AccountValueLabelText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        AccountValueLabelText.setText("Account Balance");

        javax.swing.GroupLayout AccountValueBoxLayout = new javax.swing.GroupLayout(AccountValueBox);
        AccountValueBox.setLayout(AccountValueBoxLayout);
        AccountValueBoxLayout.setHorizontalGroup(
            AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountValueBoxLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountValueBoxLayout.createSequentialGroup()
                        .addComponent(AccountValueLabel)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountValueBoxLayout.createSequentialGroup()
                        .addComponent(AccountValueLabelText)
                        .addGap(90, 90, 90))))
        );
        AccountValueBoxLayout.setVerticalGroup(
            AccountValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountValueBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AccountValueLabelText)
                .addGap(31, 31, 31)
                .addComponent(AccountValueLabel)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        StockValueBox.setBackground(new java.awt.Color(255, 255, 255));
        StockValueBox.setPreferredSize(new java.awt.Dimension(406, 227));
        StockValueBox.setSize(new java.awt.Dimension(406, 227));

        PortfolioBalanceLabelText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 25)); // NOI18N
        PortfolioBalanceLabelText.setText("Portfolio Balance");

        PortfolioBalanceLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 60)); // NOI18N
        PortfolioBalanceLabel.setText("$5,000");

        javax.swing.GroupLayout StockValueBoxLayout = new javax.swing.GroupLayout(StockValueBox);
        StockValueBox.setLayout(StockValueBoxLayout);
        StockValueBoxLayout.setHorizontalGroup(
            StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockValueBoxLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PortfolioBalanceLabel)
                    .addComponent(PortfolioBalanceLabelText))
                .addGap(91, 91, 91))
        );
        StockValueBoxLayout.setVerticalGroup(
            StockValueBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockValueBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PortfolioBalanceLabelText)
                .addGap(29, 29, 29)
                .addComponent(PortfolioBalanceLabel)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PortfolioTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 50)); // NOI18N
        PortfolioTitleLabel.setText("Portfolio");

        StocksLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 50)); // NOI18N
        StocksLabel.setText("Stocks");

        javax.swing.GroupLayout PortfolioPanelLayout = new javax.swing.GroupLayout(PortfolioPanel);
        PortfolioPanel.setLayout(PortfolioPanelLayout);
        PortfolioPanelLayout.setHorizontalGroup(
            PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortfolioPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PortfolioPanelLayout.createSequentialGroup()
                        .addComponent(StocksLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PortfolioPanelLayout.createSequentialGroup()
                        .addComponent(PortfolioTitleLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PortfolioPanelLayout.createSequentialGroup()
                        .addComponent(StockValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(AccountValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        PortfolioPanelLayout.setVerticalGroup(
            PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortfolioPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PortfolioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccountValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PortfolioPanelLayout.createSequentialGroup()
                        .addComponent(PortfolioTitleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(StockValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(StocksLabel)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PortfolioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PortfolioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StockMarketButtonEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketButtonEnter
        // HOVERED    
        this.SidebarStockMarketBox.setBackground(Color.BLACK);
        this.SidbarStockMarketLabel.setForeground(Color.WHITE);
        
        //unhovered
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
        
        //unhovered
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_StockMarketButtonEnter

    private void StockMarketButtonExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketButtonExit
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_StockMarketButtonExit

    private void SidebarPortfolioBoxEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPortfolioBoxEnter
        //unhovered
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
        
        //HOVER
        this.SidebarPortfolioBox.setBackground(Color.BLACK);
        this.SidebarPortfolioLabel.setForeground(Color.WHITE);
        
        //unhovered
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarPortfolioBoxEnter

    private void SidebarPortfolioBoxExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPortfolioBoxExit
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarPortfolioBoxExit

    private void SidebarWatchlistBoxEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarWatchlistBoxEnter
        //unhovered      
        this.SidebarStockMarketBox.setBackground(Color.WHITE);
        this.SidbarStockMarketLabel.setForeground(Color.BLACK);
        
        //unhovered
        this.SidebarPortfolioBox.setBackground(Color.WHITE);
        this.SidebarPortfolioLabel.setForeground(Color.BLACK);
        
        //HOVERED
        this.SidebarWatchlistBox.setBackground(Color.BLACK);
        this.SidebarWatchlistLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_SidebarWatchlistBoxEnter

    private void SidebarWatchlistBoxExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarWatchlistBoxExit
        this.SidebarWatchlistBox.setBackground(Color.WHITE);
        this.SidebarWatchlistLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_SidebarWatchlistBoxExit

    private void StockMarketPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMarketPressed
        this.PortfolioPanel.setVisible(false);
        
    }//GEN-LAST:event_StockMarketPressed

    private void PortfolioPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PortfolioPressed
        // TODO add your handling code here:
    	this.PortfolioPanel.setVisible(true);
    }//GEN-LAST:event_PortfolioPressed
    private void none(java.awt.event.MouseEvent evt){}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountValueBox;
    private javax.swing.JLabel AccountValueLabel;
    private javax.swing.JLabel AccountValueLabelText;
    private javax.swing.JLabel PortfolioBalanceLabel;
    private javax.swing.JLabel PortfolioBalanceLabelText;
    private javax.swing.JPanel PortfolioPanel;
    private javax.swing.JLabel PortfolioTitleLabel;
    private javax.swing.JLabel SidbarStockMarketLabel;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel SidebarPortfolioBox;
    private javax.swing.JLabel SidebarPortfolioLabel;
    private javax.swing.JPanel SidebarStockMarketBox;
    private javax.swing.JPanel SidebarWatchlistBox;
    private javax.swing.JLabel SidebarWatchlistLabel;
    private javax.swing.JPanel StockValueBox;
    private javax.swing.JLabel StocksLabel;
    // End of variables declaration//GEN-END:variables
}